#!/usr/bin/env perl
use strict; use warnings; use v5.38;
# wrap proc_multitilt.bash to find approprate directories in scratch area
# only input is directory with raw data (scp upload from windows/scanner console)

use File::Glob ':bsd_glob';
use File::Basename 'dirname';
use Cwd 'abs_path', 'cwd';

my $scriptdir = dirname(abs_path(__FILE__));
my $def_angle =  "$scriptdir/angle.txt";
my $n_angle = 10;

die "must specify upload/session directory as first and only argument" if $#ARGV != 0;
chdir $ARGV[0] or die "bad input directory '$ARGV[0]'. $!";
my @seqs;
for my $d  (split /\0/, qx/find -maxdepth 1 -mindepth 1 -type d -print0/) {
  my @f=split /\0/, qx/find $d -mindepth 1 -type f -not -iname '.*' -print0/;
  my ($seqno,$pname,$aname,$phmag) = split /\s+/, qx/dicom_hinfo -tag 0020,0011 -tag 0018,0024 -tag 0018,1030 -tag 0051,1016 -no_name $f[0]/;
  push @seqs, {seqno=>$seqno, pname=>$pname, aname=>$aname, phmag=>$phmag, n=>$#f+1, d=>$d, ex=>$f[0]};
}
my (%epi, %mag, %phase) = ((),(),());
@seqs = sort {$a->{seqno} <=> $b->{seqno}} @seqs;
for my $seq (@seqs){
  if(not $epi{d} and ($seq->{pname} =~ /epfid2d1/) and $seq->{n} eq $n_angle){
    %epi=%$seq;
    #print "epi found $epi{d}: $seq->{pname} like epfid2d1 $seq->{n}==$n_angle\n";
  } elsif ((not $mag{d}) && ($seq->{pname} =~ /fm2d2r/) && ($seq->{aname} =~ /GRE/) && $seq->{phmag} =~ m:M/ND: ){
    %mag=%{$seq};
  } elsif ((not $phase{d}) && ($mag{d}) && ($seq->{pname} =~ /fm2d2r/) && $seq->{aname} =~ /GRE/ && $seq->{phmag} =~ m:P/ND: and $mag{seqno}+1 == $seq->{seqno}){
     %phase=%$seq;
  }
  last if %phase && %mag && %epi;

}
die "ERROR: no mtilt 'epfid2d1' epi with $n_angle volume (matching angle.txt) in `pwd`" unless -d $epi{d};
die "ERROR: no GRE mag 'fm2d2r' M/ND in `pwd`" unless -d $mag{d};
die "ERROR: no GRE phase 'fm2d2r' P/ND in `pwd`; have mag at seqno $mag{seqno}" unless -d $phase{d};

use Data::Dumper 'Dumper';
say Dumper({e=>\%epi,m=>\%mag,p=>\%phase});
system(qq($scriptdir/proc_multitilt.bash -mtilt $epi{d} -mag $mag{d} -phase $phase{d} -out `pwd`/dcm-best-tilt))
