MTR:
	pp -o MTR MultiTiltRemote.pl

.ONESHELL:
SHELL = /usr/bin/bash
~/perl5/lib/perl5/PAR/:
	cpanm --local-lib=~/perl5 local::lib && eval $(shell perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
	cpanm PAR::Packer
